apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "python"

  links:
    - url: https://github.com/ItRachii/aws-elasticbeanstalk-20231110111310
      title: "python"
      icon: code

  labels:
    system: web-apps
    trackid: "aws-elasticbeanstalk-20231110111310"
    environmentname: test-copilot-env

  tags:
    - python
    - aws
    - "applicationtype-webapplication"

  annotations:
    # add elastic beanstalk annotation
    jenkins.io/github-folder: 'custom-actions/tf-python'
    github.com/project-slug: ItRachii/aws-elasticbeanstalk-20231110111310
    backstage.io/techdocs-ref: dir:.
    backstage.io/linguist: https://github.com/ItRachii/ebs-sample-python-application
    sonarqube.org/project-key: 'python-app/aws-elb-python'

spec:
  type: service
  lifecycle: experimental
  system: elasticbeanstalk
  owner: "group:default/ey"
